# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: ^envs_manager/tests/env_files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
